version: "3.9"
services:
    mongodb5:
        image: mongo:5.0.0
        container_name: mongodb5
        hostname: mongodb5
        volumes:
            - /etc/mongod.conf:/etc/mongod.conf
            - /srv/mongodb5/data/:/data/db/
        env_file:
            - .env
        ports:
            - "27117:27017"
        logging:
            options:
                max-size: 1g
        command: ["-f", "/etc/mongod.conf"]
        restart: unless-stopped
        deploy:
            mode: replicated
            replicas: 1
            placement:
              constraints: [node.hostname == server1]
            resources:
              limits:
                cpus: '6.0'
                memory: 1024M
              reservations:
                cpus: '1.0'
                memory: 512M

