version: '3'

services:
  mongodb_cluster_docker1:
    image: ubuntu:focal
    environment:
      - TZ=America/Denver
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=sisko@7660$boo
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    network_mode: host
    volumes:
      - mongocerts_docker1:/mongocerts
      - mongodata_docker1:/data/db
      - mongoconf_docker1:/mongoconf
      - mongoconfigdb_docker1:/data/configdb
      - mongologs_docker1:/var/log/mongodb
      - mongoscripts_docker1:/scripts
    tty: true
    stdin_open: true
    command: ["/scripts/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 512M          
      placement:
        constraints:
          - node.hostname == docker1

volumes:
  mongocerts_docker1:
    external: true
  mongodata_docker1:
    external: true
  mongoconf_docker1:
    external: true
  mongoconfigdb_docker1:  
    external: true
  mongologs_docker1:
    external: true
  mongoscripts_docker1:
    external: true
