version: '3'

services:
  ssh_box_securex:
    image: ubuntu:focal
    container_name: ssh_box_securex
    environment:
      - TZ=America/Denver
    volumes:
      - /mnt/FourTB/__projects_server1/portainer-ce/docker/ssh-box-securex/workspaces:/workspaces
    ports:
      - 2222:2222
    tty: true
    stdin_open: true
    #command: ["ls -la"] # /workspaces/entrypoint.sh
    #command: >
    #    bash -c "python manage.py migrate
    #    && python manage.py runserver 0.0.0.0:8000"
    logging:
        options:
            max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
    restart: unless-stopped
