version: '3.9'

services:
  dropbox:
    image: ubuntu:focal
    container_name: dropbox
    volumes:
      - dropbox_volume:/dropbox
      - ./entrypoint.sh:/workspaces/entrypoint.sh
    environment:
      - PYTHONUNBUFFERED=1
    logging:
        options:
            max-size: 1g
    restart: always
    command: ["/workspaces/entrypoint.sh"]
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
    network_mode: 'host'

volumes:
  dropbox_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/dropbox