version: '3.9'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://${HOSTIP}:9001 --tlsskipverify
    environment:
      - ./.env
    ports:
      - "${P9000}:9000"
      - "${P8000}:8000"
    volumes:
      - ${portainer_data}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
