version: '3'

services:
  docker-deployer:
    image: ubuntu:focal
    container_name: docker-deployer
    environment:
      - TZ=America/Denver
    volumes:
      - ./entrypoint.sh:/workspaces/entrypoint.sh
      - ./.env:/workspaces/.env
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    tty: true
    stdin_open: true
    #command: ["/workspaces/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 1024M
    restart: "no"
