version: "3.9"
services:
    mongodb5:
        image: mongo:5.0.0
        container_name: mongodb5
        hostname: mongodb5
        volumes:
            - ./etc/mongod.conf:/etc/mongod.conf
            - /opt/mongodb5/data/:/data/db/
            - /opt/mongodb5/mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        ports:
            - "27117:27017"
        logging:
            options:
                max-size: 1g
        command: ["-f", "/etc/mongod.conf"]
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '6.0'
                    memory: 1512M

