#!/bin/bash

# https://dev.to/efe136/how-to-enable-mongodb-authentication-with-docker-compose-2nbp

cname="mongo1" 

docker service create --limit-cpu "4.0" --limit-memory "2g" --dns "109.201.133.196" --reserve-cpu "3.0" --reserve-memory "512m" --replicas 1 --network host --mount type=volume,source=mongodata1,target=/data/db --mount type=volume,source=mongoconf1,target=/etc/mongod.conf  --mount type=volume,source=mongoconfigdb1,target=/data/configdb --mount type=volume,source=mongocerts1,target=/mongocerts --mount type=volume,source=mongologs1,target=/var/log/mongodb --constraint 'node.hostname == server1' --name mongo1 mongo:5.0.1-focal --replSet "rs0" --auth --keyFile "/mongocerts/keyfile.txt" #--config "/etc/mongod.conf/mongod.conf"
docker service create --limit-cpu "4.0" --limit-memory "2g" --dns "109.201.133.196" --reserve-cpu "3.0" --reserve-memory "512m" --replicas 1 --network host --mount type=volume,source=mongodata2,target=/data/db --mount type=volume,source=mongoconf2,target=/etc/mongod.conf  --mount type=volume,source=mongoconfigdb2,target=/data/configdb --mount type=volume,source=mongocerts2,target=/mongocerts --mount type=volume,source=mongologs2,target=/var/log/mongodb --constraint 'node.hostname == tp01-2066' --name mongo2 mongo:5.0.1-focal --replSet "rs0" --auth --keyFile "/mongocerts/keyfile.txt" #--config "/etc/mongod.conf/mongod.conf"
docker service create --limit-cpu "4.0" --limit-memory "2g" --dns "109.201.133.196" --reserve-cpu "3.0" --reserve-memory "512m" --replicas 1 --network host --mount type=volume,source=mongodata_docker1,target=/data/db --mount type=volume,source=mongoconf_docker1,target=/etc/mongod.conf  --mount type=volume,source=mongoconfigdb_docker1,target=/data/configdb --mount type=volume,source=mongocerts_docker1,target=/mongocerts --mount type=volume,source=mongologs_docker1,target=/var/log/mongodb --constraint 'node.hostname == docker1' --name mongo3 mongo:5.0.1-focal --replSet "rs0" --auth --keyFile "/mongocerts/keyfile.txt" #--config "/etc/mongod.conf/mongod.conf"
docker service create --limit-cpu "4.0" --limit-memory "2g" --dns "109.201.133.196" --reserve-cpu "3.0" --reserve-memory "512m" --replicas 1 --network host --mount type=volume,source=mongodata_docker2,target=/data/db --mount type=volume,source=mongoconf_docker2,target=/etc/mongod.conf  --mount type=volume,source=mongoconfigdb_docker2,target=/data/configdb --mount type=volume,source=mongocerts_docker2,target=/mongocerts --mount type=volume,source=mongologs_docker2,target=/var/log/mongodb --constraint 'node.hostname == docker2' --name mongo4 mongo:5.0.1-focal --replSet "rs0" --auth --keyFile "/mongocerts/keyfile.txt" #--config "/etc/mongod.conf/mongod.conf"

#CID=$(docker ps -qf "name=$cname")
#echo "CID=$CID"
