version: "3.9"
services:
    mongodb5:
        image: mongo:latest
        container_name: mongodb5
        hostname: mongodb5
        env_file:
            - .env
        ports:
            - "27117:27017"
        logging:
            options:
                max-size: 1g
        volumes:
            - type: volume
              source: mongoconf1
              target: /etc
            - type: volume
              source: mongodata1
              target: /data/db
        command: ["-f", "/etc/mongodb.conf"]
        restart: unless-stopped
        deploy:
            mode: replicated
            replicas: 1
            placement:
              constraints: [node.labels.mongo.replica == 1]
            resources:
                limits:
                    cpus: '6.0'
                    memory: 1512M
