version: '3.9'

services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sisko@7660$boo  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - seafile_mysql:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    logging:
        options:
            max-size: 1g
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    logging:
        options:
            max-size: 1g
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6                
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "${PORT}:80"
      - "${PORT2}:443"
    volumes:
      - seafile_data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=10.5.0.5
      - DB_ROOT_PASSWD=sisko@7660$boo  # Requested, the value shuold be root's password of MySQL service.
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=raychorn@gmail.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=0rang3z3bra     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.web-service.org # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    logging:
        options:
            max-size: 1g
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 512M
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7                

volumes:
    seafile_data:
        external: true
        name: seafile_data
    seafile_mysql:
        external: true
        name: seafile_mysql

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1  