version: "3.8"

services:
  python_runner2:
    image: raychorn/ubuntu_focal_all_pythons:latest-3.9.6
    volumes:
        - cloudns_refresher_volume:/workspaces
    entrypoint:
        - /bin/bash
    ports:
        - "9999:9000"
    stdin_open: true
    command: ["/workspaces/makevenv.sh"]
    logging:
        options:
            max-size: 1g
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 128M
        replicas: 2
        placement:
            max_replicas_per_node: 1
        update_config:
            parallelism: 2
            delay: 10s
            order: stop-first
    restart_policy:
        condition: on-failure
        