version: "3.8"

services:
  python_runner2:
      image: ubuntu:focal
      restart: unless-stopped
      volumes:
          - ./code:/workspaces/python_runner/
          - ./requirements.txt:/workspaces/requirements.txt
          - ./entrypoint.sh:/workspaces/entrypoint.sh
      tty: true
      stdin_open: true
      #command: ["/workspaces/makevenv.sh"]
      logging:
          options:
              max-size: 1g
      deploy:
          resources:
              limits:
                  cpus: '1.0'
                  memory: 256M
