version: "3.8"

services:
  python_runner2:
      image: 10.0.0.173:5000/ubuntu_focal_all_pythons:latest-3.9.6
      restart: unless-stopped
      volumes:
          - ./code:/workspaces/python_runner/
          - ./makevenv.sh:/workspaces/makevenv.sh
          - ./requirements.txt:/workspaces/requirements.txt
      entrypoint:
          - /bin/bash
      ports:
       - "9999:9000"
      tty: true
      stdin_open: true
      command: ["/workspaces/makevenv.sh"]
      logging:
          options:
              max-size: 1g
      deploy:
          resources:
              limits:
                  cpus: '1.0'
                  memory: 256M
