version: "3.8"

services:
  python_runner2:
    image: ubuntu:focal
    volumes:
        - ./code:/workspaces/python_runner/
        - ./scripts:/workspaces/scripts/
        - ./requirements.txt:/workspaces/requirements.txt
        - ./entrypoint.sh:/workspaces/entrypoint.sh
    stdin_open: true
    environment:
      - TZ=America/Denver
    command: ["/workspaces/entrypoint.sh"]
    logging:
        options:
            max-size: 1g
    deploy:
        resources:
            limits:
                cpus: '1.0'
                memory: 256M
        replicas: 2
        placement:
            max_replicas_per_node: 1
        update_config:
            parallelism: 2
            delay: 10s
            order: stop-first
            failure_action: continue
                