version: "3.9"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./etc/mongod.conf:/etc/mongod.conf
            - /opt/mongodb/data/:/data/db/
            - /opt/mongodb/mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        ports:
            - "27017:27017"
        logging:
            options:
                max-size: 1g
        command: ["-f", "/etc/mongod.conf"]
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 512M

