version: '3.3'

services:
  docker-deployer:
    image: tower.web-service.org:5000/ubuntu-focal-minimal:latest
    container_name: docker-deployer
    volumes:
      - ./workspaces:/workspaces
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
    #entrypoint: /workspaces/entrypoint.sh
    logging:
        options:
            max-size: 1g
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2048M
    restart: unless-stopped
